### ISSUE TITLE
why your kernel size is 3 not 3*i+3?

### ISSUE THREAD

**Issue by JullyZ** [developer0hye/SKNet-PyTorch#3]
https://github.com/developer0hye/SKNet-PyTorch/blob/1cef097179b24654ac02910b0af4399c0830c703/sknet.py#L25

**Comment by developer0hye** [comment]
Look at the "dilation=1+i".
You can feel it.

**Comment by EdwinKuo1337** [comment]
In case anyone has the same question, the original paper also stated on Page 3, section 3.1, under Split, that:
For further efficiency, the conventional convolution with a 5×5 kernel is replaced with the dilated convolution with a 3×3 kernel and dilation size 2.
