### ISSUE TITLE
the number of feature maps

### ISSUE THREAD

**Issue by creater-zq** [developer0hye/SKNet-PyTorch#5]
Thanks you! 
In line 121和122:
1. your code: 
` self.stage_1 = self._make_layer(64, 128, 128, nums_block=nums_block_list[0], stride=strides_list[0])`    
 `self.stage_2 = self._make_layer(128, 256, 512, nums_block=nums_block_list[1], stride=strides_list[1])`

2. but I think as follows  according to Table 1 in paper：
`self.stage_1 = self._make_layer(64, 128, 256, nums_block=nums_block_list[0], stride=stride_list[0])`    
`self.stage_2 = self._make_layer(256, 256, 512, nums_block=nums_block_list[1], stride=stride_list[1])`

**Comment by developer0hye** [comment]
@creater-zq 
Thanks! You're right. I modified code.
